name: Testing-Ubuntu

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: |
        dotnet restore UI/Thoughts.UI.MVC
        dotnet restore Services/Thoughts.WebAPI
      
    - name: Build
      run:  |
        dotnet build --no-restore UI/Thoughts.UI.MVC
        dotnet build --no-restore Services/Thoughts.WebAPI
      
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
